---
sudo: false
language: node_js
node_js:
  - 0.12.7
before_install:
  - gem update --system
  - gem install compass
script: grunt
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
